os: linux
language: python
python: "3.7"
dist: xenial
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8.0
          packages:
            - clang-8.0
      env:
        - MATRIX_EVAL="CC=clang-8.0 && CXX=clang++-8.0"

before_install:
  - export CC
  - export CXX
  - eval "${MATRIX_EVAL}"
install:
  - pip install conan
  - conan user
script:
  - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -j $(nproc)
  - ctest .
