dist: xenial
language: cpp
compiler:
  - gcc
install:
  - pip install --user conan
  - conan user
script:
  - export PY_USER_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
  - export PATH=$PY_USER_BIN:$PATH
  - cmake . -G "Unix Makefiles"
  - cmake --build .
  - ctest
